name: Codespell
on:
  merge_group:
    types: [checks_requested]
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: dev
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/cache@v3
        name: Setup Python cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run pre-commit
        run: |
          pre-commit install
          SKIP=no-commit-to-branch pre-commit run --all-files
